services:
  diwali-be:
    image: diwali.azurecr.io/diwali-be-app:1.1.3
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.dev.properties
    ports:
      - "3000:3000"
    restart: always