# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diwali-be-deployment
  labels:
    app: diwali-be
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: diwali-be
  template:
    metadata:
      labels:
        app: diwali-be
    spec:
      containers:
      - name: diwali-be-container
        image: poornagollakoti/diwali-be:1.0.0  # Replace with your Docker image
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: backend-configmap-dev
        - secretRef:
            name: backend-secret-dev
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: "/health"
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: diwali-be-service
  labels:
    app: diwali-be
spec:
  type: ClusterIP  # You can change it to LoadBalancer for external access
  selector:
    app: diwali-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001