# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diwali-be-deployment
  labels:
    app: diwali-be
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: diwali-be  # label by which pod can be selected
  template:
    metadata:
      labels:
        app: diwali-be # label by which pod can be selected
    spec:
      containers:
      - name: diwali-be
        image: diwali.azurecr.io/diwali-be-app:1.1.1  # Replace with your Docker image
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: backend-configmap-dev
        - secretRef:
            name: backend-secret-dev
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "128Mi"
        #     cpu: "250m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: diwali-be-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "product_service_rg"
  labels:
    app: diwali-be-service
spec:
  type: LoadBalancer  # You can change it to LoadBalancer for external access
  loadBalancerIP: 52.190.10.71 # Replace with your static IP
  selector:
    app: diwali-be # select the pod and expose
  ports:
    - protocol: TCP
      port: 3000 # The service exposes the application externally on this port
      targetPort: 3000 # Forward traffic to the application's port inside the container